spring.application.name=pedidos360-backend

# Azure AD resource server config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/77747a67-519b-49e8-a701-13c4e011672c/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://cca6baa4-4933-4d00-b8a9-8c899dbfba57

# Database H2 (Development)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
