spring.application.name=pedidos360-backend

# Azure AD resource server config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/77747a67-519b-49e8-a701-13c4e011672c/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://cca6baa4-4933-4d00-b8a9-8c899dbfba57
